# PyMOL Visualization Script for dCTP_variant_048 binding to dCTP
# Generated by nucleotide binder pipeline
# To use: pymol -c this_script.pml

# Load structure
load /home/thinkingscopeanalysis/nucleotide_catchers/scripts/../specificity_library/screening_results/dCTP_variant_048_vs_dCTP/boltz_results_dCTP_variant_048_vs_dCTP/predictions/dCTP_variant_048_vs_dCTP/dCTP_variant_048_vs_dCTP_model_0.cif, complex

# Color by chain
color wheat, chain A  # Protein
color green, chain B  # Ligand

# Show protein as cartoon
hide everything, chain A
show cartoon, chain A
set cartoon_fancy_helices, 1

# Show ligand as sticks
hide everything, chain B
show sticks, chain B
set stick_radius, 0.3, chain B

# Highlight CDR3 region (residues 95-101)
color orange, chain A and resi 95-101
show sticks, chain A and resi 95-101

# Show binding interface residues (within 5Å of ligand)
select binding_site, chain A within 5 of chain B
show sticks, binding_site
color cyan, binding_site

# Add labels for key mutations
label chain A and resi 96 and name CA, "96"
label chain A and resi 97 and name CA, "97"
label chain A and resi 98 and name CA, "98"
label chain A and resi 100 and name CA, "100"

# Show hydrogen bonds
distance hbonds, (chain A), (chain B), 3.5, mode=2
hide labels, hbonds

# Set up view
bg_color white
set ray_shadows, 0
set antialias, 2
set orthoscopic, 1

# Zoom to binding site
zoom binding_site, 5

# Save images
png /home/thinkingscopeanalysis/nucleotide_catchers/scripts/../specificity_library/visualizations/dCTP_variant_048_dCTP_overview.png, width=1200, height=900, dpi=300
zoom binding_site, 2
png /home/thinkingscopeanalysis/nucleotide_catchers/scripts/../specificity_library/visualizations/dCTP_variant_048_dCTP_binding_site.png, width=1200, height=900, dpi=300

# Rotate and save another view
rotate y, 90
png /home/thinkingscopeanalysis/nucleotide_catchers/scripts/../specificity_library/visualizations/dCTP_variant_048_dCTP_side_view.png, width=1200, height=900, dpi=300

# Save session
save /home/thinkingscopeanalysis/nucleotide_catchers/scripts/../specificity_library/visualizations/dCTP_variant_048_dCTP.pse

print "Visualization complete! Images saved to /home/thinkingscopeanalysis/nucleotide_catchers/scripts/../specificity_library/visualizations/"
