#!/usr/bin/env python3
"""
Visualize and analyze binding structures from Boltz predictions.

This script creates PyMOL visualization scripts and analyzes binding interfaces.
"""

import sys
import json
from pathlib import Path
import numpy as np

def create_pymol_visualization_script(variant_id, target_nucleotide, cif_file, output_dir):
    """Create a PyMOL script to visualize the binding interface."""

    pymol_script = f"""# PyMOL Visualization Script for {variant_id} binding to {target_nucleotide}
# Generated by nucleotide binder pipeline
# To use: pymol -c this_script.pml

# Load structure
load {cif_file}, complex

# Color by chain
color wheat, chain A  # Protein
color green, chain B  # Ligand

# Show protein as cartoon
hide everything, chain A
show cartoon, chain A
set cartoon_fancy_helices, 1

# Show ligand as sticks
hide everything, chain B
show sticks, chain B
set stick_radius, 0.3, chain B

# Highlight CDR3 region (residues 95-101)
color orange, chain A and resi 95-101
show sticks, chain A and resi 95-101

# Show binding interface residues (within 5Å of ligand)
select binding_site, chain A within 5 of chain B
show sticks, binding_site
color cyan, binding_site

# Add labels for key mutations
label chain A and resi 96 and name CA, "96"
label chain A and resi 97 and name CA, "97"
label chain A and resi 98 and name CA, "98"
label chain A and resi 100 and name CA, "100"

# Show hydrogen bonds
distance hbonds, (chain A), (chain B), 3.5, mode=2
hide labels, hbonds

# Set up view
bg_color white
set ray_shadows, 0
set antialias, 2
set orthoscopic, 1

# Zoom to binding site
zoom binding_site, 5

# Save images
png {output_dir}/{variant_id}_{target_nucleotide}_overview.png, width=1200, height=900, dpi=300
zoom binding_site, 2
png {output_dir}/{variant_id}_{target_nucleotide}_binding_site.png, width=1200, height=900, dpi=300

# Rotate and save another view
rotate y, 90
png {output_dir}/{variant_id}_{target_nucleotide}_side_view.png, width=1200, height=900, dpi=300

# Save session
save {output_dir}/{variant_id}_{target_nucleotide}.pse

print "Visualization complete! Images saved to {output_dir}/"
"""

    return pymol_script


def analyze_binding_interface(result_data):
    """Analyze the binding interface from prediction results."""

    analysis = {
        'variant_id': result_data['variant_id'],
        'target': result_data['target_nucleotide'],
        'confidence_metrics': {
            'confidence_score': result_data['confidence']['confidence_score'],
            'ligand_iptm': result_data['confidence']['ligand_iptm'],
            'complex_plddt': result_data['confidence']['complex_plddt'],
        },
        'mutations': result_data['mutations'],
        'prediction_time': result_data.get('elapsed_time', 'N/A')
    }

    return analysis


def create_all_visualizations(library_dir):
    """Create visualization scripts for all top binders."""

    library_dir = Path(library_dir)
    results_dir = library_dir / "screening_results"
    output_dir = library_dir / "visualizations"
    output_dir.mkdir(exist_ok=True)

    # Load screening results
    with open(results_dir / "screening_results.json", 'r') as f:
        results = json.load(f)

    # Top binders
    top_binders = [
        ("dATP_variant_039", "dATP"),
        ("dGTP_variant_019", "dGTP"),
        ("dCTP_variant_048", "dCTP"),
        ("dTTP_variant_016", "dTTP")
    ]

    print("=" * 80)
    print("CREATING VISUALIZATION SCRIPTS FOR TOP BINDERS")
    print("=" * 80)
    print()

    all_analyses = []

    for variant_id, target_nucleotide in top_binders:
        print(f"Processing {variant_id} vs {target_nucleotide}...")

        # Find the result
        result = None
        for r in results['results'] if isinstance(results, dict) and 'results' in results else results:
            if r['variant_id'] == variant_id and r['test_nucleotide'] == target_nucleotide:
                result = r
                break

        if not result:
            print(f"  ⚠ Result not found, skipping...")
            continue

        # Find CIF file
        pred_name = f"{variant_id}_vs_{target_nucleotide}"
        cif_pattern = results_dir / pred_name / f"boltz_results_{pred_name}" / "predictions" / pred_name / f"{pred_name}_model_0.cif"

        if not cif_pattern.exists():
            print(f"  ⚠ Structure file not found: {cif_pattern}")
            continue

        # Create PyMOL script
        pymol_script = create_pymol_visualization_script(
            variant_id, target_nucleotide, str(cif_pattern.absolute()), str(output_dir.absolute())
        )

        script_file = output_dir / f"visualize_{variant_id}_{target_nucleotide}.pml"
        with open(script_file, 'w') as f:
            f.write(pymol_script)

        print(f"  ✓ PyMOL script: {script_file.name}")

        # Analyze binding interface
        analysis = analyze_binding_interface(result)
        all_analyses.append(analysis)

        print(f"  ✓ Confidence: {result['confidence']['confidence_score']:.3f}")
        print(f"  ✓ Ligand iPTM: {result['confidence']['ligand_iptm']:.3f}")
        print()

    # Create master visualization script
    master_script = output_dir / "visualize_all_binders.pml"
    with open(master_script, 'w') as f:
        f.write("""# Master PyMOL script to visualize all top binders
# Usage: pymol -c visualize_all_binders.pml

# This script will load and visualize all 4 top binders sequentially

""")
        for variant_id, target_nucleotide in top_binders:
            f.write(f"# {variant_id} vs {target_nucleotide}\n")
            f.write(f"@visualize_{variant_id}_{target_nucleotide}.pml\n\n")

    print("=" * 80)
    print("VISUALIZATION SCRIPTS CREATED")
    print("=" * 80)
    print()
    print(f"Location: {output_dir}/")
    print()
    print("To visualize:")
    print("  1. Install PyMOL: https://pymol.org/")
    print("  2. Run: pymol visualize_<variant>_<nucleotide>.pml")
    print("  3. Or run all: pymol -c visualize_all_binders.pml")
    print()
    print("PyMOL scripts will:")
    print("  • Color protein as cartoon (wheat)")
    print("  • Show ligand as sticks (green)")
    print("  • Highlight CDR3 mutations (orange)")
    print("  • Show binding site residues (cyan)")
    print("  • Display hydrogen bonds")
    print("  • Save high-resolution PNG images")
    print("  • Save PyMOL session (.pse file)")
    print()

    # Create analysis summary
    summary_file = output_dir / "binding_analysis_summary.json"
    with open(summary_file, 'w') as f:
        json.dump(all_analyses, f, indent=2)

    print(f"Binding analysis summary: {summary_file}")
    print()

    return all_analyses


if __name__ == "__main__":
    if len(sys.argv) > 1:
        library_dir = sys.argv[1]
    else:
        library_dir = "../specificity_library"

    create_all_visualizations(library_dir)
